/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectorestaurante.vistas;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectorestaurante.AccesoAdatos.MesaData;
import proyectorestaurante.AccesoAdatos.MeseroData;
import proyectorestaurante.AccesoAdatos.PedidoData;
import proyectorestaurante.AccesoAdatos.ProductoData;
import proyectorestaurante.entidades.Mesa;
import proyectorestaurante.entidades.Mesero;
import proyectorestaurante.entidades.Pedido;
import proyectorestaurante.entidades.Producto;

/**
 *
 * @author pc
 */
public class PedidosVista extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo1 = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    private DefaultTableModel modelo2 = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    private MesaData mesaData = new MesaData();
    private Mesa mesa = new Mesa();
    private MeseroData meseroData=new MeseroData();
    private Mesero mesero= new Mesero();
    private ProductoData productoData= new ProductoData();
    private Producto producto= new Producto();
    private ArrayList<Producto> listaProducto;
    private Pedido pedido;
    private PedidoData pedidoData= new PedidoData();
    private ArrayList<Pedido> listaPedidos;
    /**
     * Creates new form PedidosVista
     */
    public PedidosVista() {
        initComponents();
        armarCabecera1();
        armarCabecera2();
        cargarMesas();
        cargarMeseros();
        armarTablaP();
        pedido = new Pedido();
        listaPedidos=new ArrayList<>();
        hora.setText(""+LocalTime.now().getHour());
        minuto.setText(""+LocalTime.now().getMinute());
        jCfecha.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMesa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProducto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tPedido = new javax.swing.JTable();
        Total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMesero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        Hora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        minuto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCfecha = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Realizacion de Pedidos");

        cbMesa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tProducto.setBackground(new java.awt.Color(255, 255, 255));
        tProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tProducto);

        tPedido.setBackground(new java.awt.Color(255, 255, 255));
        tPedido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPedidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tPedido);

        Total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Total.setText("0");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total:$ ");

        cbMesero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMeseroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mesero:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mesa:");

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/GuardarTodo.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Hora.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 255, 255));
        Hora.setText("Hora:");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha:");

        hora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hora.setText("00");

        minuto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minuto.setText("00");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText(":");

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Productos");

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pedido");

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/pedidos.png"))); // NOI18N
        jLabel8.setText("Administracion de Pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Hora)
                                .addGap(18, 18, 18)
                                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minuto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(7, 7, 7)
                                .addComponent(Total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Guardar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbMesero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(128, 128, 128))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cbMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hora)
                            .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(minuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMeseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMeseroActionPerformed

    private void tProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tProductoMouseClicked
        // TODO add your handling code here:
        try{
        mesa=(Mesa) cbMesa.getSelectedItem();
        mesero=(Mesero) cbMesero.getSelectedItem();
        LocalTime horaPedido=LocalTime.of(Integer.parseInt(hora.getText()), Integer.parseInt(minuto.getText()));
        LocalDate fechaPedido=jCfecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int fila = tProducto.getSelectedRow();
        if(fila >=0){
            int x=(int)modelo1.getValueAt(fila,0);
            producto=productoData.buscarProductoporCodigo(x);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione producto");
        }
        pedido=new Pedido(0, mesa.getIdMesa(), mesero.getIdMesero(), producto.getIdProducto(), 1 , fechaPedido, horaPedido, false, false);
        GuardarPedido(pedido,producto);
        CargarTotal();
         } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al agregar el producto al pedido: " + ex.getMessage());
    }
    }//GEN-LAST:event_tProductoMouseClicked

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        try{
        for(Pedido x:listaPedidos){
            pedidoData.guardarPedido(x);
            stock(x);
        }
        listaPedidos=new ArrayList<>();
        recargar();
        } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar pedidos: " + ex.getMessage());
    }
    }//GEN-LAST:event_GuardarActionPerformed

    private void tPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPedidoMouseClicked
        // TODO add your handling code here:
        try{
        int fila = tPedido.getSelectedRow();
        if(fila >=0){
            int x=(int)modelo2.getValueAt(fila,0);
            producto=productoData.buscarProductoporCodigo(x);
            eliminarProducto(producto);
            CargarTotal();
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione producto");
        }
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Error al eliminar el producto del pedido: " + ex.getMessage());
        }
    }//GEN-LAST:event_tPedidoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Total;
    private javax.swing.JComboBox<Mesa> cbMesa;
    private javax.swing.JComboBox<Mesero> cbMesero;
    private javax.swing.JTextField hora;
    private com.toedter.calendar.JDateChooser jCfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField minuto;
    private javax.swing.JTable tPedido;
    private javax.swing.JTable tProducto;
    // End of variables declaration//GEN-END:variables


    private void armarCabecera1(){
        ArrayList<Object> columnas = new ArrayList<>();
        modelo1.addColumn("Codigo");
        modelo1.addColumn("Nombre");
        modelo1.addColumn("Precio");
        modelo1.addColumn("Stock");
        tProducto.setModel(modelo1);
    }
    
    private void armarCabecera2() {
        ArrayList<Object> columnas = new ArrayList<>();
        modelo2.addColumn("Codigo");
        modelo2.addColumn("Nombre");
        modelo2.addColumn("Precio");
        modelo2.addColumn("Cantidad");
        tPedido.setModel(modelo2);
    }
    
    public void cargarMesas(){
        for(Mesa m : mesaData.listarMesas())
               cbMesa.addItem(m);
     }
    
    public void cargarMeseros(){
        for(Mesero m : meseroData.listarMeseros())
               cbMesero.addItem(m);
    }
    
    private void armarTablaP(){
        listaProducto=(ArrayList<Producto>) productoData.listarProductos();
        for(Producto x:listaProducto){
            modelo1.addRow(new Object[]{x.getCodigo(),x.getNombreProducto(),x.getPrecio(),x.getStock()});
        }
    }
    
    private void armarTabla(){
        for(Pedido x:listaPedidos){
            Producto pro=productoData.buscarProductoporId(x.getIdProducto());
            modelo2.addRow(new Object[]{pro.getCodigo(),pro.getNombreProducto(),pro.getPrecio()*x.getCantidadProducto(),x.getCantidadProducto()});
        }
    }
    
    private void borrarFilas() {
        int filas = tPedido.getRowCount() - 1;

        for (int f = filas; f >= 0; f--) {
            modelo2.removeRow(f);
        }
    }
    
    private void borrarFilas2() {
        int filas = tProducto.getRowCount() - 1;

        for (int f = filas; f >= 0; f--) {
            modelo1.removeRow(f);
        }
    }
    
    private void GuardarPedido(Pedido x,Producto y){
        try{
        int z= listaPedidos.size();
        int p=0;
        for(int i=0;i<z;i++){
            if(listaPedidos.get(i).getIdProducto()==x.getIdProducto()){
                Pedido a=listaPedidos.get(i);
                if(y.getStock()>a.getCantidadProducto()){
                a.setCantidadProducto(a.getCantidadProducto()+1);
                listaPedidos.set(i, a);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Stock insuficiente: "+y.getNombreProducto()+"="+y.getStock());
                }
                borrarFilas();
                armarTabla();
                p=p+1;
            }
        }
        if(p==0){
             if (y.getStock() > 0){
            listaPedidos.add(x);
            borrarFilas();
            armarTabla();
             }else {
                JOptionPane.showMessageDialog(this, "Stock insuficiente: " + y.getNombreProducto() + " = " + y.getStock());
            }
        }
        } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar el pedido: " + ex.getMessage());
    }
    }
    
    private void CargarTotal(){
        int z=0;
        for(Pedido x:listaPedidos){
            Producto pro=productoData.buscarProductoporId(x.getIdProducto());
            z=z+(pro.getPrecio()*x.getCantidadProducto());
        }
        Total.setText(""+z);
    }
    
    private void eliminarProducto(Producto pedidoE){
        try{
        int z=listaPedidos.size();
        for(int i=0;i<z;i++){
            if(listaPedidos.get(i).getIdProducto()==pedidoE.getIdProducto()){
                if(listaPedidos.get(i).getCantidadProducto()>1){
                   Pedido a=listaPedidos.get(i);
                    a.setCantidadProducto(a.getCantidadProducto()-1);
                    listaPedidos.set(i, a);
                    borrarFilas();
                    armarTabla();
                }
                else{
                    listaPedidos.remove(i);
                    borrarFilas();
                    armarTabla();
                    break;
                }
            }
        }
    }catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al eliminar el producto del pedido: " + ex.getMessage());
    }
}
    
    private void recargar(){
        borrarFilas();
        borrarFilas2();
        armarTablaP();
        Total.setText(""+0);
    }
    
    private void stock(Pedido pe){
        try{
        for(Producto x:listaProducto){
            if(x.getIdProducto()==pe.getIdProducto()){
                x.setStock(x.getStock()-pe.getCantidadProducto());
                productoData.modificarProducto(x);
            } 
//            else {
//                    JOptionPane.showMessageDialog(this, "Stock insuficiente: " + x.getNombreProducto());
//                }
        }
    }catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al actualizar el stock: " + ex.getMessage());
    }
}
}