/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectorestaurante.vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Lourdes
 */
public class Restaurante extends javax.swing.JFrame {

    /**
     * Creates new form Restaurante
     */
    public Restaurante() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        ImageIcon icono =new ImageIcon(getClass().getResource("/ProyectoRestaurante/recursos/escritorioproyecto.jpg"));
        Image miImagen = icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);
            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        PEDIDOS = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setForeground(new java.awt.Color(102, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/menu.png"))); // NOI18N
        jMenu2.setText("MENU");
        jMenu2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N

        jMenuItem4.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/platos.png"))); // NOI18N
        jMenuItem4.setText("PLATOS");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        PEDIDOS.setBackground(new java.awt.Color(255, 255, 255));
        PEDIDOS.setForeground(new java.awt.Color(102, 0, 0));
        PEDIDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/restaurantes.png"))); // NOI18N
        PEDIDOS.setText("PEDIDOS");
        PEDIDOS.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        PEDIDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PEDIDOSActionPerformed(evt);
            }
        });

        jMenuItem5.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/pedidos.png"))); // NOI18N
        jMenuItem5.setText("PEDIDOS ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        PEDIDOS.add(jMenuItem5);

        jMenuItem6.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem6.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/gestion-de-crisis.png"))); // NOI18N
        jMenuItem6.setText("GESTION DE PEDIDOS");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        PEDIDOS.add(jMenuItem6);

        jMenuBar1.add(PEDIDOS);

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setForeground(new java.awt.Color(102, 0, 0));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/sala.png"))); // NOI18N
        jMenu5.setText("MESAS");
        jMenu5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N

        jMenuItem9.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem9.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/mesa.png"))); // NOI18N
        jMenuItem9.setText("MESAS");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem11.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem11.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jMenuItem11.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/pedido-en-linea.png"))); // NOI18N
        jMenuItem11.setText("PEDIDOS DE MESAS");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setForeground(new java.awt.Color(102, 0, 0));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/camarero.png"))); // NOI18N
        jMenu4.setText("MESEROS");
        jMenu4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N

        jMenuItem7.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem7.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/lupa.png"))); // NOI18N
        jMenuItem7.setText("INFORMACION");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem10.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem10.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/ordenar-comida.png"))); // NOI18N
        jMenuItem10.setText("Pedidos por meseros");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setForeground(new java.awt.Color(102, 0, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/money.png"))); // NOI18N
        jMenu3.setText("CAJA");
        jMenu3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N

        jMenuItem8.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem8.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/proyecto-de-ley.png"))); // NOI18N
        jMenuItem8.setText("COBRAR");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem14.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem14.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jMenuItem14.setForeground(new java.awt.Color(255, 51, 51));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorestaurante/recursos/dolar.png"))); // NOI18N
        jMenuItem14.setText("PEDIDOS PAGOS");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.LEADING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        MesaVista mesa = new MesaVista();
        mesa.setVisible(true);
        //ga.getContentPane().setBackground(new Color(0,153,204));
        escritorio.add(mesa);
        escritorio.moveToFront(mesa);

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        MeseroV mesero = new MeseroV();
        mesero.setVisible(true);
         mesero.getContentPane().setBackground(new Color(255,153,102));
        escritorio.add(mesero);
        escritorio.moveToFront(mesero);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ProductoV pro = new ProductoV();
        pro.setVisible(true);
         pro.getContentPane().setBackground(new Color(255,153,102));
        escritorio.add(pro);
        escritorio.moveToFront(pro);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void PEDIDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PEDIDOSActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_PEDIDOSActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        PedidosVista pedido = new PedidosVista();
        pedido.setVisible(true);
        pedido.getContentPane().setBackground(new Color(255,153,102));
        escritorio.add(pedido);
        escritorio.moveToFront(pedido);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        PedidosEstado pedido = new PedidosEstado();
        pedido.setVisible(true);
        pedido.getContentPane().setBackground(new Color(255,153,102));
        escritorio.add(pedido);
        escritorio.moveToFront(pedido);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        PedidosMeseroVista listaMesero = new PedidosMeseroVista();
        listaMesero.setVisible(true);
        listaMesero.getContentPane().setBackground(new Color(255,153,102));
        escritorio.add(listaMesero);
        escritorio.moveToFront(listaMesero);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        PedidoMesaVista listaMesa = new PedidoMesaVista();
        listaMesa.setVisible(true);
        listaMesa.getContentPane().setBackground(new Color(255,153,102));
        escritorio.add(listaMesa);
        escritorio.moveToFront(listaMesa);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:        
        escritorio.removeAll();
        escritorio.repaint();
        PagosFecha pago = new PagosFecha();
        pago.setVisible(true);
        pago.getContentPane().setBackground(new Color(255,153,102));
        escritorio.add(pago);
        escritorio.moveToFront(pago);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        CajaVista caja = new CajaVista();
        caja.setVisible(true);
        caja.getContentPane().setBackground(new Color(255,153,102));
        escritorio.add(caja);
        escritorio.moveToFront(caja);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu PEDIDOS;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
